# Generated by Django 3.2 on 2022-02-23 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0007_auto_20220210_1858'),
        ('mainapp', '0007_auto_20220214_1454'),
    ]

    operations = [
    ]
