# Generated by Django 4.0.1 on 2022-02-14 07:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authnapp', '0002_alter_shopuser_activation_key_expires'),
        ('authnapp', '0002_user_model_extend'),
    ]

    operations = [
    ]
