# Generated by Django 3.2 on 2022-02-14 14:54

import datetime

from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ("authnapp", "0003_merge_20220214_0743"),
    ]

    operations = [
        migrations.AlterField(
            model_name="shopuser",
            name="activation_key_expires",
            field=models.DateTimeField(
                default=datetime.datetime(2022, 2, 16, 14, 54, 10, 213623, tzinfo=utc),
                verbose_name="актуальность ключа",
            ),
        ),
    ]
